name: "📚 Проблема с документацией"
description: Сообщайте о проблемах в нашей документации
labels: 
- Docs
body:
- type: textarea
  attributes: 
    label: Предоставьте описание запрашиваемых изменений документации
    placeholder: Кратко опишите, какой документ необходимо исправить и почему.
  validations:
    required: true