name: Linux

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        cxx: [g++-9, g++-10, clang++-10, clang++-11, clang++-12]
        standard: [17, 20]
        build_type: [Debug, Release]

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt install -y libgtest-dev

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure
      working-directory: ${{runner.workspace}}/build
      env:
        CXX: ${{matrix.cxx}}
      run: |
        cmake -DCMAKE_CXX_STANDARD=${{matrix.standard}} \
              -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
              $GITHUB_WORKSPACE

    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: |
        threads=`nproc`
        cmake --build . --config ${{matrix.build_type}} --parallel $threads

    - name: Run tests
      working-directory: ${{runner.workspace}}/build
      run: |
        threads=`nproc`
        ctest --parallel $threads
